[package]
name = "kas-7guis"
version = "0.1.0"
authors = ["Diggory Hardy <git@dhardy.name>"]
edition = "2021"
resolver = "2"
publish = false

[dependencies]
kas = { version = "0.17.0", features = ["view"] }
chrono = "0.4"
env_logger = "0.11.8"
pest = "2.1"
pest_derive = "2.1"
